// var now = new Date();

// toDateString()
// getDate()
// getFullYear()
// getMonth()
// getDay()
// getHours()
// getMinutes()
// getSeconds()
// getTimezoneOffset()
// getMilliseconds()
// setDate()
// setFullYear()
// setHours()
// setMilliseconds()
// setMinutes()
// setMonth()
// setSeconds()

